# 端口
server:
  port: 9001

spring:
  application:
    name: cloud-gateway
  ## GateWay配置
  cloud:
    gateway:
      routes: #多个路由
        - id: payment_routh  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名

          # uri+predicates  要访问这个路径得先经过9001处理
          #          uri: http://localhost:8001  # 匹配成功后提供服务的路由地址
          # lb 属于GateWay 的关键字，代表是动态uri，即代表使用的是服务注册中心的微服务名，它默认开启使用负载均衡机制
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由

        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: cloud-eureka-server
  client:
    # true表示向注册中心注册自己
    register-with-eureka: true
    # true表示自己需要注册，# 注册进 eureka Server # 网关他本身也是一个微服务，也要注册进注册主中心
    fetch-registry: true
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:8761/eureka
