# 端口
server:
  port: 9001

spring:
  application:
    name: cloud-gateway
  ## GateWay配置
  cloud:
    gateway:
      routes: #多个路由
        - id: payment_routh  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名

          # uri+predicates  要访问这个路径得先经过9001处理
          #          uri: http://localhost:8001  # 匹配成功后提供服务的路由地址
          # lb 属于GateWay 的关键字，代表是动态uri，即代表使用的是服务注册中心的微服务名，它默认开启使用负载均衡机制
          # 可以有多个微服务，例如：cloud-order-service，cloud-goods-service，通过一个网关层
          uri: lb://cloud-payment-service
          predicates:
            - Path=/api/payment/get/**  # 断言，路径相匹配的进行路由，**可以多级路径，*单一路径
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          # 将跳转路径中包含的/api替换成空
          # 访问http://ip1:9001/api/payment/get/1就是访问http://ip2:8001/payment/get/1
          # 拓展：访问http://ip1:9001/api/order/get/1就是访问http://ip3:8001/order/get/1
          # 一般来说：线上都是分布式部署+集群，以实现高性能，所以都是每个服务器部署一个服务，即多个服务间ip不同，但是端口相同，通过网关统一转发到各个服务的对应接口
          # 本地开发是单机模式，所以只能是多个服务ip相同，但是端口不同来进行开发测试

        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: cloud-eureka-server
  client:
    # true表示向注册中心注册自己
    register-with-eureka: true
    # true表示自己需要注册，# 注册进 eureka Server # 网关他本身也是一个微服务，也要注册进注册主中心
    fetch-registry: true
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:8761/eureka
